### ISSUE TITLE
Immediate status request after armed alarm

### ISSUE THREAD

**Issue by aferrato** [augustas2/eldes#1]
Hello and thank you for this integration!
it would be useful that when the alarm is armed / disarmed, a request for the status of the alarm is immediately made to understand whether it has actually been activated or not.

At this moment if I armed the alarm, but there are open zones and it does not activate, HA shows the status only after the pooling time set in the configuration.

**Comment by augustas2** [comment]
Hi, thanks for the feedback! I understand the problem.

Currently if something unnexpected happens during arm/disarm API call, the new status is still set to state. So this is definetly a bug.

I will make a fix after a weekend.

**Comment by augustas2** [comment]
Fixed in #2

**Comment by evaliukonis** [comment]
You can not request status immediately after arm/disarm action. To complete action need time and must wait status from cloud. For better performance use 10 or 15 sec pool time.
