### ISSUE TITLE
[Feature request] sensors support

### ISSUE THREAD

**Issue by nobless** [augustas2/eldes#10]
Hello, very nice integration!

Any plans on adding motion, doors, windows sensors to home assistant as sensors?

**Comment by samuolis** [comment]
> Hello, very nice integration!
> 
> Any plans on adding motion, doors, windows sensors to home assistant as sensors?

There is a problem that eldes application are not providing such data and eldes as company is not providing more details or any help, so at this moment there is no possibility to add them, maybe in future they will open such api

**Comment by nobless** [comment]
maybe it could be done via Ethernet communicator ELAN3-ALARM and their app Eldes Utility, there are many valuable information provided, and even don't need connect to their cloud.

It's a shame that they doesn't provide any information about this :(

motion sensors would be very nice addition to HA!

**Comment by samuolis** [comment]
Yeah this addition would be really good.

Maybe someone will investigate this and would add addition to these sensors

**Comment by augustas2** [comment]
Yep Eldes Utility provides a lot of information about sensors and so on. But unfortunately Eldes API not. So this integration will not support sensors until they will not be added to Eldes API.

I heard that somebody was working with ELAN3-ALARM integration, but there is no public integration.
