### ISSUE TITLE
Error adding entities for domain switch with platform eldes_alarm

### ISSUE THREAD

**Issue by drawgas** [augustas2/eldes#14]
Logger: homeassistant.components.switch
Source: custom_components/eldes_alarm/switch.py:65
Integration: Switch (documentation, issues)
First occurred: 08:57:11 (2 occurrences)
Last logged: 08:57:11

Error adding entities for domain switch with platform eldes_alarm
Error while setting up eldes_alarm platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 615, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/eldes_alarm/switch.py", line 65, in icon
    return OUTPUT_ICONS_MAP[self.data["outputs"][self.entity_index]["iconName"]]
KeyError: None

**Comment by drawgas** [comment]
@augustas2 Gal gali užmesti akį?

**Comment by augustas2** [comment]
Sveikas, ok pažiūrėsiu per savaitgalį.

**Comment by augustas2** [comment]
Klaidą meta kai pirmą kartą setup darai? Kokie pas tave output prietaisai yra ant eldes signalizacijos (gali matyti "Automatika" tab'e per Eldes app)?

**Comment by augustas2** [comment]
Pabandyk pakeist šito failo turinį ant savo HA serverio su šituo: https://github.com/augustas2/eldes/blob/switch-icon-fix/custom_components/eldes_alarm/switch.py

Duok žinot ar veikia :)

**Comment by drawgas** [comment]
Klaidą meta reguliariai (po restarto / reload'o). Nuo pat setupo pradžios prieš n mėnesių nemačiau output'ų (tuomet ir nereikėjo) :)

Fix'as padėjo - jokios klaidos ir matomi output'ai. Ačiū
