### ISSUE TITLE
Help with start  compounent 

### ISSUE THREAD

**Issue by maksimvelbaum** [augustas2/eldes#21]
Hello everyone , Maybe stupid questions , but how to start this component , I installed it on HA over HACS, looked files code , but it is not my level of knowledge.  Any help with next steps ? Do I need to install some addditional compounens/integrations to start it ?

**Comment by samuolis** [comment]
You just Install through hacs and restart HA, then it will be as any integration in integrations page, you will need to add it with wizard

**Comment by maksimvelbaum** [comment]
Thanks! I did full restart of the system and it appears in integrations.
