### ISSUE TITLE
Not working because changed cloud API

### ISSUE THREAD

**Issue by evaliukonis** [augustas2/eldes#22]
All requests require a pin.
events/list renamed to event/list and need IMEI in payload, also have size parameter to reduce size.

If you need help I can share some changes. Can not create pull request because need fast fix and hardcoded IMEI to code.

**Comment by augustas2** [comment]
Please share the details about changes. I will take a look today in the evening and will make a fix. Also thanks for informing, havent noticed it stopped working.

**Comment by evaliukonis** [comment]
Also one problem with token refresh. It is not good do it everytime. Need improve. Do only on 403. But need change call api function. I am not python developer and do not known how is better to do.
Flow should be: call api, if 403 call refresh, if no error call again api, if error on refresh 401 need login again and call api.

**Comment by augustas2** [comment]
- Pin still not needed. Works perfectly without it.
- I see events is not working, but your provided URL is the same as it is in code `event/list?imei={imei}`, please provide correct URL
- Auth token is another story (need to refactor code, I dont have time for it until it works)

**Comment by evaliukonis** [comment]
/api/device/event/list
payload: {imei: 123, size: 10, pin: 1234}

I really can not understand how it works for you without a pin because I decompiled the Android app and also tried Postman and all requests require a pin.

**Comment by giedriuskilcauskas** [comment]
Even after update still not working, errors changing between 400 and 403

**Comment by evaliukonis** [comment]
Yes because pin is required. 403 is because to fast try to refresh token. I can share my code maybe like an attachment. With some small fixes, it works now.

**Comment by augustas2** [comment]
In iOS app pin is not used in payload thats why I did not added that. Testing events and it works without errors. Its difficult to fix a problem than I can not replicate without any debug information from you guys.

**Comment by giedriuskilcauskas** [comment]
> Yes because pin is required. 403 is because to fast try to refresh token. I can share my code maybe like an attachment. With some small fixes, it works now.

That would be very much appreciated :)

**Comment by evaliukonis** [comment]
Just use postman and you see that not working
[eldes_alarm.zip](https://github.com/augustas2/eldes/files/12669959/eldes_alarm.zip)

**Comment by augustas2** [comment]
Used postman and here is the proof :D How do you think iOS app works?

![image](https://github.com/augustas2/eldes/assets/7789787/3876b0ca-53a8-4acf-8b98-876798ddd74f)

**Comment by augustas2** [comment]
Also most of the endpoints can be tested here on their mobile app: https://cloud.eldesalarms.com:8083

**Comment by giedriuskilcauskas** [comment]
> Also most of the endpoints can be tested here on their mobile app: https://cloud.eldesalarms.com:8083

Even this one asks for PIN :-) My assumption would be that they distinguish between Android vs iPhone and request PIN or not.

**Comment by augustas2** [comment]
> > Also most of the endpoints can be tested here on their mobile app: https://cloud.eldesalarms.com:8083
> 
> Even this one asks for PIN :-) My assumption would be that they distinguish between Android vs iPhone and request PIN or not.

Yes it asks for pin, and you can enter whatever you want it is not even passed in network tab 😄

**Comment by giedriuskilcauskas** [comment]
> > > Also most of the endpoints can be tested here on their mobile app: https://cloud.eldesalarms.com:8083
> > 
> > 
> > Even this one asks for PIN :-) My assumption would be that they distinguish between Android vs iPhone and request PIN or not.
> 
> Yes it asks for pin, and you can enter whatever you want it is not even passed in network tab 😄

Looking at network tab I can see pin as payload for each call

**Comment by augustas2** [comment]
> > > > Also most of the endpoints can be tested here on their mobile app: https://cloud.eldesalarms.com:8083
> > > 
> > > 
> > > Even this one asks for PIN :-) My assumption would be that they distinguish between Android vs iPhone and request PIN or not.
> > 
> > 
> > Yes it asks for pin, and you can enter whatever you want it is not even passed in network tab 😄
> 
> Looking at network tab I can see pin as payload for each call

Nothing in this one:
![image](https://github.com/augustas2/eldes/assets/7789787/f1d0149a-79d7-499a-92a3-2b83ebc9e41e)

**Comment by augustas2** [comment]
Ok I see there is PIN on another ones, but still it loads even I add "0000" 😄

**Comment by augustas2** [comment]
Ok will add pin parameter for those needed endpoints later today.

**Comment by giedriuskilcauskas** [comment]
> Ok I see there is PIN on another ones, but still it loads even I add "0000" 😄

It loads main page, but not going further with wrong PIN:
![image](https://github.com/augustas2/eldes/assets/75305866/898c50b3-4fba-46c0-8cad-ea453ce2efb2)

**Comment by augustas2** [comment]
> > Ok I see there is PIN on another ones, but still it loads even I add "0000" 😄
> 
> It loads main page, but not going further with wrong PIN: ![image](https://user-images.githubusercontent.com/75305866/269207302-898c50b3-4fba-46c0-8cad-ea453ce2efb2.png)

Interesting. For me everything in zones, temperatures are loaded with any pin I provide. Ok I will not spend more time investigating why Eldes endpoints behave like that, just will add a pin parameter and it would solve these issues.

**Comment by giedriuskilcauskas** [comment]
> > > Ok I see there is PIN on another ones, but still it loads even I add "0000" 😄
> > 
> > 
> > It loads main page, but not going further with wrong PIN: ![image](https://user-images.githubusercontent.com/75305866/269207302-898c50b3-4fba-46c0-8cad-ea453ce2efb2.png)
> 
> Interesting. For me everything in zones, temperatures are loaded with any pin I provide. Ok I will not spend more time investigating why Eldes endpoints behave like that, just will add a pin parameter and it would solve these issues.

In a nutshell, it's crap :-) With wrong pin it just timeouts, with correct pin just got this:
![image](https://github.com/augustas2/eldes/assets/75305866/103737b5-ae1c-46c5-bca2-2376499ea002)
And I keep getting such cases with app as well :(

**Comment by evaliukonis** [comment]
Maybe you use an owner account or you use another model of the alarm system. The PIN is okay for me for any account that is registered in the alarm system. If I use my own pin it says that I am armed. If I use my wife say that wife armed. But it does not depend on account credentials.
The PIN should be correct for me too. I attached the working code just there is no migration and I modified HA settings files manually or you can register a new integration.

**Comment by evaliukonis** [comment]
PIN will be added? or maybe you can merge my code?
I can not use already existing code and only modified working.

**Comment by augustas2** [comment]
PIN changes coming. Not going to replace code without looking whats inside, also your changes does not include workflow changes, it breaks existing integration (devices). When integrations gets updated it should ask for reconfiguration. Will release when ready.

**Comment by evaliukonis** [comment]
I also added a refresh token new logic. It works better and does not need a refresh every time. You can add it too.
I know problems with breaking changes but do not know how should be implemented.
