### ISSUE TITLE
Issue with arm/disarm

### ISSUE THREAD

**Issue by evaliukonis** [augustas2/eldes#3]
You arm or disarm alarm system. It show state but after response from cloud reset to state before. After some time get new response and show again new state. Maybe possible add arming_time? https://www.home-assistant.io/integrations/manual#arming_time

**Comment by augustas2** [comment]
The link you provided is for custom Alarm integration. It does not have any relations to alarm panel integrations/entities.
Here is the developer docs for alarm https://developers.home-assistant.io/docs/core/entity/alarm-control-panel.

Is this issue exist in latest version v1.0.1?
So as I understand alarm does not arm and resets to previous state?
Any errors in log?

**Comment by evaliukonis** [comment]
I set 15sec sync time on integration. 
I call arm service. Alarm panel show armed but Eldes alarm system still disarmed status. 
After few seconds Alarm panel show disarmed. 
After few seconds Elder alarm system go to armed state. 
Alarm panel show again armed state

This problems exists because in HA alarm panel state changed after call arm service, but real security system still disarmed and it arm only after several seconds. If integration call Eldes API in this short interval we get disarmed state

**Comment by augustas2** [comment]
Thanks for info, but still haven't received all answers from you.

Integration version?
Any errors in log?

Why this is important? Because I have made some fixes in v1.0.1 for state updates.

**Comment by evaliukonis** [comment]
version 1.0.1
no errors

For example create automatic to unlock door after Alarm system disarmed. Door unlocked but system still armed. You open and alarm systemd trigger alarm.
Another example create automatic turn on lighs after disarm and turn it off after arm. Light on after few seconds off and then again on

**Comment by augustas2** [comment]
I'm also using automations based on alarm states and never received false results.
Here is my automation trigger example after disarming alarm:

![image](https://user-images.githubusercontent.com/7789787/151815560-1b9f688f-9cad-4ff4-afec-5dd349f39725.png)


And automation trigger then alarm is armed:

![image](https://user-images.githubusercontent.com/7789787/151816399-3564e6da-a7f9-40a0-aec2-44dc4bd16ff6.png)


Can you share yours with lights on/off?

**Comment by evaliukonis** [comment]
Oh you use from state. I try your solution. Possible it works for me too.

**Comment by evaliukonis** [comment]
It works. I do not knonw about arming and disarming states.

**Comment by augustas2** [comment]
I will update documentation with usage examples later. I just was too lazy to do that earlier. 😀

**Comment by evaliukonis** [comment]
Not working your solution if you lock with Eldes app

**Comment by augustas2** [comment]
And it wont work, because Eldes is limited with 3 states - armed_home, armed_away and triggered. While my integration has 5 states - arming, disarming and same as eldes. So no way to handle via state trigger.

I’m only using HA, so this is not a case for me.

**Comment by evaliukonis** [comment]
I have small kids and they using direct keyboard. I must use both.

**Comment by augustas2** [comment]
I will check possibility to trigger by device not state. This would support both ways. I will write about update 🙂

**Comment by evaliukonis** [comment]
I arm with HA and state changed to armed_away but armed status still false. After several seconds it change to true. If I disarm state change to disarmed bus armed still true.
I think that arming must be until armed or armStay is false and disarming until armed or armStay is true. It solve my problem in this issue and also works with Eldes app.

Another problem left that sometimes state changed to unavailable. I think if Eldes cloud do not send response. I set condition on automatic to check from_state != unavailable and fix it.

**Comment by evaliukonis** [comment]
I created Pull Request. Now wait status from Eldes cloud. It works a little better because do not show wrong state while alarm system action not completed

**Comment by augustas2** [comment]
I investigated this issue today. I also set up my automations to use device trigger (should trigger by alarm keyboard or Eldes app) and it works unexpected. Alarm turns on & turns off lights in no reason after automation is triggered. Also Eldes app starts showing incorrect state.

I also checked your changes, but basically it does not solve the problem completely.

What I found that Eldes API returns HTTP status which was unexpected. I need to handle this correctly. So I will make more investigations and will try to fix that.

Until then, feel free to modify it for your needs.

**Comment by evaliukonis** [comment]
Yes it do not solve this problem but it solve wrong status. You have wait status from API or send req to API after set actionl.

**Comment by evaliukonis** [comment]
You try arm and set arming on HA, but one motion sensor or door is trigered and Arm failed. Eldes always return disarmed and thats all. I can not found way how to know failed action or not. In eldes application you get notification that one zone is trigger and maybe you want disable it.
