### ISSUE TITLE
Arming requires code

### ISSUE THREAD

**Issue by nelgi** [augustas2/eldes#33]
Arming does not function after update to HA2024.6.0

Error:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:283
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:08:14 (1 occurrences)
Last logged: 23:08:14

[139997023508880] Arming requires a code but none was given for alarm_control_panel.zonename

**Comment by keeema** [comment]
Same for me

**Comment by augustas2** [comment]
Should be able to check this issue tomorrow. Will update to new a version too 😀

**Comment by augustas2** [comment]
New version ([v1.0.12](https://github.com/augustas2/eldes/releases/tag/v1.0.12)) was released with a fix.
