### ISSUE TITLE
Stop working with Error 403

### ISSUE THREAD

**Issue by evaliukonis** [augustas2/eldes#5]
Unknown error occurred during Eldes update request: 403, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/list')

**Comment by evaliukonis** [comment]
This problem because token expired. (Token can expire if no internet in longer period and can not refresh token). Also possible get this problem if login with account to android application or direct to Eldes cloud website. All old tokens including refresh tokens will be revoked.

Solution: 
- do login if failed refresh token request
- refresh token before all request to cloud

**Comment by augustas2** [comment]
I will take a look into all problems next week.
